# Generated by Django 2.2 on 2019-05-19 13:00

from django.db import migrations, models

from mainsite.models.enum import RecordStatusEnum, GenderEnum


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_link_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('first_name2', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('last_name2', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('other_name', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('gender', models.CharField(max_length=11, blank=False, null=False, default=GenderEnum.UNSPECIFIED, choices=GenderEnum.choices())),
                ('actual_birthday', models.DateTimeField(blank=True, null=True)),
                ('estimated_birthday', models.DateTimeField(blank=True, null=True)),
                ('medical_concern', models.CharField(blank=False, default="Food allergy: nothing", max_length=50, null=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum.ACTIVE, max_length=10)),
            ],
            options={
                'db_table': 'mainsite_attendees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
