# Generated by Django 2.2 on 2019-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(db_index=True, max_length=20)),
                ('english_name', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.NullBooleanField(db_index=True, default=False, help_text='NULL means deleted')),
            ],
            options={
                'ordering': ['english_name', 'chinese_name'],
            },
        ),
    ]
