# Generated by Django 2.2.5 on 2019-09-19 04:53

from django.db import migrations, models
import mainsite.models.enum
import mainsite.models.utility


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('DELETED', 'deleted'), ('ARCHIVED', 'archived')], db_index=True, default=mainsite.models.enum.RecordStatusEnum('active'), max_length=10)),
            ],
            options={
                'db_table': 'mainsite_organizations',
            },
            bases=(models.Model, mainsite.models.utility.Utility),
        ),
    ]
