# Generated by Django 2.2 on 2019-05-19 13:01

from django.db import migrations, models
import django.db.models.deletion
from  mainsite.models.enum import RecordStatusEnum, AttendingProgramEnum


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=999999, max_digits=8)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('attending_type', models.CharField(max_length=20, null=True)),
                ('attending_program', models.CharField(choices=AttendingProgramEnum.choices(), db_index=True, null=True, default=AttendingProgramEnum.NONE, max_length=30)),
                ('belief', models.CharField(max_length=20, null=True)),
                ('bed_needs', models.IntegerField(default=1)),
                ('mobility', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum.ACTIVE, max_length=10)),
                ('address', models.ManyToManyField(to='mainsite.Address')),
                ('attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.Attendee')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.Registration')),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
    ]
