# Generated by Django 2.2 on 2019-08-26 15:41

from django.db import migrations, models
import mainsite.models.enum
from mainsite.models.enum import RecordStatusEnum
import mainsite.models.formatter


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidProgramProgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('display_order', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=mainsite.models.enum.RecordStatusEnum('active'), max_length=10)),
            ],
            options={
                'db_table': 'mainsite_kid_program_progression',
            },
        ),
    ]
