# Generated by Django 2.2 on 2019-08-27 13:55

from django.db import migrations, models

from mainsite.models.enum import RecordStatusEnum


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidProgramLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_program_group', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='mainsite.KidProgramGroup')),
                ('kid_program_progression', models.ForeignKey(on_delete=models.SET(0), to='mainsite.KidProgramProgression')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('location_type', models.CharField(max_length=50)),
                ('location_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum.ACTIVE, max_length=10)),
            ],
            options={
                'db_table': 'mainsite_kid_program_lessons',
            },
        ),
        migrations.AddConstraint(
            model_name='kidprogramlesson',
            constraint=models.UniqueConstraint(fields=('kid_program_group_id', 'location_type', 'location_id', 'start_time'), name='uniq_group_location_time'),
        ),
    ]
