# Generated by Django 2.2 on 2019-08-29 04:30

from django.db import migrations, models

from mainsite.models.enum import RecordStatusEnum


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_kidprogramlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_attendee', models.ForeignKey(on_delete=models.SET(0), related_name='primary', to='mainsite.Attendee')),
                ('other_attendee', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='relative', to='mainsite.Attendee')),
                ('relation_to_main', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum.ACTIVE, max_length=10)),
            ],
            options={
                'db_table': 'mainsite_relationships',
            },
        ),
    ]
