# Generated by Django 2.2.5 on 2019-09-14 00:52

from django.db import migrations, models

from mainsite.models.enum import RecordStatusEnum


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_program_session_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_attendee', models.ForeignKey(on_delete=models.SET(0), related_name='from_attendee', to='mainsite.Attendee')),
                ('to_attendee', models.ForeignKey(on_delete=models.SET(0), related_name='to_attendee', to='mainsite.Attendee')),
                ('relation', models.CharField(db_index=True, max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum('active'), max_length=10)),
            ],
            options={
                'db_table': 'mainsite_relationships',
            },
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('from_attendee', 'to_attendee'), name='from_attendee_to_attendee'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='relatives',
            field=models.ManyToManyField(related_name='_attendee_relatives_+', through='mainsite.Relationship', to='mainsite.Attendee'),
        ),
    ]
