# Generated by Django 2.2.4 on 2019-09-06 14:01

from django.db import migrations, models

from mainsite.models.enum import RecordStatusEnum


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=models.SET(0), to='mainsite.Event')),
                ('address', models.ForeignKey(on_delete=models.SET(0), to='mainsite.Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum.ACTIVE, max_length=10)),
            ],
            options={
                'db_table': 'mainsite_event_addresses',
            },
        ),
        migrations.AddConstraint(
            model_name='eventaddress',
            constraint=models.UniqueConstraint(fields=('event', 'address'), name='event_address'),
        ),
    ]
