# Generated by Django 2.2.5 on 2019-09-12 05:48

from django.db import migrations, models

from mainsite.models.enum import RecordStatusEnum


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_event_address_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendingDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.ForeignKey(on_delete=models.SET(0), to='mainsite.Attending')),
                ('division', models.ForeignKey(on_delete=models.SET(0), to='mainsite.Division')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum.ACTIVE, max_length=10)),
            ],
            options={
                'db_table': 'mainsite_attending_divisions',
            },
        ),
        migrations.AddConstraint(
            model_name='attendingdivision',
            constraint=models.UniqueConstraint(fields=('attending', 'division'), name='attending_division'),
        ),
        migrations.AddField(
            model_name='attending',
            name='divisions',
            field=models.ManyToManyField(through='mainsite.AttendingDivision', to='mainsite.Division'),
        ),
        migrations.AddField(
            model_name='division',
            name='attendings',
            field=models.ManyToManyField(through='mainsite.AttendingDivision', to='mainsite.Attending'),
        ),
    ]
