# Generated by Django 2.2.5 on 2019-09-12 05:57

from django.db import migrations, models

from mainsite.models.enum import RecordStatusEnum


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_attending_division_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=models.SET(0), to='mainsite.Address')),
                ('attending', models.ForeignKey(on_delete=models.SET(0), to='mainsite.Attending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum.ACTIVE, max_length=10)),
            ],
            options={
                'db_table': 'mainsite_attending_addresses',
            },
        ),
        migrations.AddConstraint(
            model_name='attendingaddress',
            constraint=models.UniqueConstraint(fields=('attending', 'address'), name='attending_address'),
        ),
        migrations.AddField(
            model_name='address',
            name='attendings',
            field=models.ManyToManyField(through='mainsite.AttendingAddress', to='mainsite.Attending'),
        ),
        migrations.AddField(
            model_name='attending',
            name='addresses',
            field=models.ManyToManyField(through='mainsite.AttendingAddress', to='mainsite.Address'),
        ),
    ]
