# Generated by Django 2.2.5 on 2019-09-19 15:25

from django.db import migrations, models

from mainsite.models.enum import RecordStatusEnum


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='ProgramTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_session', models.ForeignKey(on_delete=models.SET(0), to='mainsite.ProgramSession')),
                ('site_type', models.ForeignKey(help_text='location: django_content_type id for table name', on_delete=models.SET(0), to='contenttypes.ContentType')),
                ('site_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(blank=True, default=0, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=RecordStatusEnum.choices(), db_index=True, default=RecordStatusEnum.ACTIVE, max_length=10)),
            ],
            options={
                'db_table': 'mainsite_program_teams',
            },
        ),
    ]
    dependencies = [
        ('mainsite', '0021_attending_address_m2m'),
    ]

